### ISSUE TITLE
won't compile

### ISSUE THREAD

**Issue by powerpuffboysz** [heyjoeway/Genesis-Plus-GX#5]
i followed the compile instructions to the letter but keep getting errors
![Screenshot (1)](https://user-images.githubusercontent.com/11527009/109046629-cef9b300-7689-11eb-9c6e-cd97adbb79bc.png)

**Comment by heyjoeway** [comment]
Fixed some things in the process of getting Github Actions set up, pull the new changes and let me know if it works.

**Comment by heyjoeway** [comment]
Gonna close this as the compilation errors that were shown have been fixed and I haven't gotten a response. Lemme know if you've still got issues and I'll reopen it.
